### ISSUE TITLE
Is this still mantained?

### ISSUE THREAD

**Issue by Fancy2209** [Imposter/otool#5]
This project doesn't get updated in a year 
Is it lack of time or is it unmaintained?

**Comment by Imposter** [comment]
Is there something specific you're asking about or is it not working? It should still work as it is at this time.
________________________________
From: Fancy2209 ***@***.***>
Sent: Thursday, May 19, 2022 5:26:03 PM
To: Imposter/otool ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Imposter/otool] Is this still mantained? (Issue #5)


This project doesn't get updated in a year
Is it lack of time or is it unmaintained?

**Comment by Fancy2209** [comment]
I just stranged at it not being updated in a year 
And reading the README downloads are quite confusing

**Comment by Imposter** [comment]
I can update that sometime in the comingweeks. Quite busy at the moment. Sorry for the confusion.
________________________________
