### ISSUE TITLE
MFA support is currently broken

### ISSUE THREAD

**Issue by Doc-4** [Imposter/otool#7]
Using this according to the instructions with MFA off results in success, using it with MFA on results in this error:
![Error](https://user-images.githubusercontent.com/60247583/176572307-e0989f09-a735-4eff-85ea-545cc140b27b.PNG)

**Comment by Imposter** [comment]
Fixed in master https://github.com/Imposter/otool/commit/8053250ff49801abe51c5cd9d464f57be3d62f4c and vu https://github.com/Imposter/otool/commit/58a5e4f6a7ca1bf4d12451f12e0a745cd307c61a
